// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Review struct {
	ID      string `json:"id"`
	Game    string `json:"game"`
	Title   string `json:"title"`
	Content string `json:"content"`
	Rating  int    `json:"rating"`
	User    *User  `json:"user"`
}

type ReviewInput struct {
	Artwork string `json:"artwork"`
	Title   string `json:"title"`
	Content string `json:"content"`
	Rating  int    `json:"rating"`
	UserID  string `json:"userId"`
}

type User struct {
	ID      string  `json:"id"`
	Name    string  `json:"name"`
	Email   string  `json:"email"`
	Friends []*User `json:"friends"`
}

type UserInput struct {
	Name    string   `json:"name"`
	Email   string   `json:"email"`
	Friends []string `json:"friends"`
}
