// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ReviewInput struct {
	ID      string `json:"id"`
	Game    string `json:"game"`
	Title   string `json:"title"`
	Content string `json:"content"`
	Rating  int    `json:"rating"`
	UserID  string `json:"userId"`
}

type UserInput struct {
	ID      string   `json:"id"`
	Name    string   `json:"name"`
	Email   string   `json:"email"`
	Friends []string `json:"friends"`
}
